import Nav from '@components/Nav';
import Head from 'next/head';
import Schedule from '@components/page-components/Schedule';

const Add = () => {
  return (
    <>
      <Head>
        <title>Add Episode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen  flex flex-col items-center">
        <Nav />
        <section className="h-full w-5/12 ">
          <Schedule />
        </section>
      </main>
    </>
  );
};

export default Add;
